sudo: required

services:
      - docker
addons:
  apt:
    packages:
      - docker-ce

before_install:

script:
    - sh build.sh

deploy:
  provider: releases
  api_key:
      secure: "s3ZoNs8h5giqRnWrCVBrFdEdJjaQBjb5EwvwgCniDg8fy2zS56ZzBC2y63GTKLbmrlKsHLjAnvcfpvK09DloHmxYlk7UEhkzUI8UEwoMzYU/+B201h0130RicmKRABcu0tqm2xHjNx05W4RXF+CnA1tdqQSzjsKZ97qekWJ8VF5P5krDVMTDplQEdDtAZe2HA/Qfs5HktHnNjkU3nf8KXoKTewQ+Yb0hLSrKT+tClZTafyIXnsse7Rv/inFKwd0CFodM9EuRV8Up5Ri8/rlF5jF4cRARnUppRlxgBoTx+uhfGLxitiycUY7lOTUtqsrsNTekOkmJchwt4lWfbXXwjMv7LA5sK8CKs6TFa32Z98W/j4wG/AEqDHygduuI2sHyO4Yr1/Y11gXOxlIeKx3dI+cUcjIeBumuKTy7xratSizoZHR4Ue1kmlmw4lpr8Rt3XEyoK2TupUJIm5Xmn4Q9gtg+GhNdHd8CkeXqbs4ab8rwYfmkAs4T9qEhV0c0rAbPldTD7HFf3iphfvZeIl9qzZWj7Ay7LXUVDG6y4Jq1guUgAiQWAkYpCUPKe3mXsTpnoQwRO5XWLpXRcSgHrWH/wGEk6Y+E7BdV/U6qy+XFf2zSdj9cgmLab+taFS8Ra3NDy1IxziMFEsNoaMVyEc2Gd9J2xplib2AyHmMx45yuMRc="
  file: 
  - ./of-watchdog
  - ./of-watchdog-armhf
  - ./of-watchdog-arm64
  - ./of-watchdog-darwin
  - ./of-watchdog.exe
  skip_cleanup: true
  on:
    tags: true
